### ISSUE TITLE
The program reports throttling issues on 0x0

### ISSUE THREAD

**Issue by RHHoek** [alwye/get_throttled#2]
When I run this program on my Pi (3B) with Raspberry Pi OS (Debian GNU/Linux 11 \n \l
) the output of  './get_throttled.sh' is
Current issues:
~ Under-voltage detected
~ Arm frequency capped
~ Currently throttled
~ Soft temperature limit active

Previously detected issues:
No throttling issues detected.

But the output of 'vcgencmd get_throttled' is
throttled=0x0

I corrected this by changing line 41 from:
if [ "$CURRENT_HEX" == "0" ]; then
with
if [ "$CURRENT_HEX" == "0" ] || [ -z $CURRENT_HEX ]; then

**Comment by mbr4cht** [comment]
+1

This comment is very valuable as it prevents from getting false positive.

I had the same issue and fell to believe that I am in throttling mode. Would highly recommend the author of this small little script to include the fix.

Thanks in advance!

**Comment by alwye** [comment]
Thanks a lot folks! I've just pushed the fix
